export class Season1Data {
    public static season1Rank = [
        {
          "Team": "Makos",
          "Record": "3W - 1D - 1L",
          "Rank": 2,
          "Captain": "Reuben",
          "Next Game": "vs Legion"
        },
        {
          "Team": "Carp",
          "Record": "3W - 2D - 0L",
          "Rank": 1,
          "Captain": "Carp",
          "Next Game": "vs Chlorine Crocs"
        },
        {
          "Team": "Legion",
          "Record": "1W - 4L",
          "Rank": 3,
          "Captain": "SK",
          "Next Game": "vs Makos"
        },
        {
          "Team": "Chlorine Crocs",
          "Record": "1W - 4L",
          "Rank": 3,
          "Captain": "Sage",
          "Next Game": "vs Carp"
        }
      ];
    public static playerStatsWeek1 = [
        {
          "Player": "Reuben",
          "Goal": 5,
          "Assist": 2,
          "Steals": 5,
          "Blocks": 0,
          "Turnovers": 2,
          "Clip": "Stl:GX010312,Goal:GX010312,Stl:GX010310,Ast:GX010310,Stl:GX010309,TO:GX010308,Goal:GX010308,Goal:GX010298,Stl:GX010300,Goal:GX010300,Stl:GX010301,TO:GX010302,Ast:GX010305,Goal:GX010307",
          "Team": "Makos",
          "Match1": "5-3 | Makos",
          "Match2": "5-0 | Makos",
          "Match3": "N/A",
          "Winner": "Makos",
          "GameTape": "https://app.box.com/s/gclsfr53u02xyjsqiho9gcdvbtiv4fsw"
        },
        {
          "Player": "James E",
          "Goal": 1,
          "Assist": 2,
          "Steals": 0,
          "Blocks": 1,
          "Turnovers": 1,
          "Clip": "blk:GX010310,Ast:GX010308,TO:GX010300,Goal:GX010304,Ast:GX010307",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Lesley",
          "Goal": 4,
          "Assist": 2,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 2,
          "Clip": "Ast:GX010312,Goal:GX010311,TO:GX010310,Goal:GX010310,Goal:GX010309,Ast:GX010300,TO:GX010303,Goal:GX010305,Stl:GX010307",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Shaneye",
          "Goal": 0,
          "Assist": 1,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "Ast:GX010298",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Manny",
          "Goal": 0,
          "Assist": 0,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 1,
          "Clip": "TO:GX010301",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Travis",
          "Goal": 0,
          "Assist": 2,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "Stl:GX010311,Ast:GX010311,Ast:GX010309",
          "Team": "Sub",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Sage",
          "Goal": 1,
          "Assist": 0,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "Goal:GX010302,Stl:GX010303",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Eddy",
          "Goal": 0,
          "Assist": 1,
          "Steals": 1,
          "Blocks": 1,
          "Turnovers": 2,
          "Clip": "TO:GX010310,Stl:GX010300,Ast:GX010301,Blk:GX010302,TO:GX010307",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Vivian",
          "Goal": 0,
          "Assist": 0,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 1,
          "Clip": "TO:GX010301",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Glenn",
          "Goal": 2,
          "Assist": 0,
          "Steals": 2,
          "Blocks": 0,
          "Turnovers": 2,
          "Clip": "TO:GX010312,Stl:GX010310,TO:GX010309,Stl:GX010308,Goal:GX010301,Goal:GX010303",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Allie",
          "Goal": 0,
          "Assist": 0,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Justin",
          "Goal": 0,
          "Assist": 1,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 3,
          "Clip": "TO:GX010311,TO:GX010310,TO:GX010300,Stl:GX010301,Ast:GX010302",
          "Team": "Sub",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Max",
          "Goal": 2,
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "5-1 | Legion",
          "Match2": "5-4 | Carp",
          "Match3": "N/A",
          "Winner": "Draw",
          "GameTape": ""
        },
        {
          "Player": "George",
          "Goal": 3,
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Kellie",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Manny",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Shae",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Eddy",
          "Goal": 1,
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "SK",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Diana",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Rachel",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Trevor",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Justin",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Sub",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        }
      ];
    public static playerStatsWeek2 = [
        {
          "Player": "Reuben",
          "Goal": 5,
          "Assist": 2,
          "Steals": 5,
          "Blocks": 0,
          "Turnovers": 2,
          "Clip": "Stl:GX010312,Goal:GX010312,Stl:GX010310,Ast:GX010310,Stl:GX010309,TO:GX010308,Goal:GX010308,Goal:GX010298,Stl:GX010300,Goal:GX010300,Stl:GX010301,TO:GX010302,Ast:GX010305,Goal:GX010307",
          "Team": "Makos",
          "Match1": "5-3 | Makos",
          "Match2": "5-0 | Makos",
          "Match3": "N/A",
          "Winner": "Makos",
          "GameTape": "https://app.box.com/s/gclsfr53u02xyjsqiho9gcdvbtiv4fsw"
        },
        {
          "Player": "James E",
          "Goal": 1,
          "Assist": 2,
          "Steals": 0,
          "Blocks": 1,
          "Turnovers": 1,
          "Clip": "blk:GX010310,Ast:GX010308,TO:GX010300,Goal:GX010304,Ast:GX010307",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Lesley",
          "Goal": 4,
          "Assist": 2,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 2,
          "Clip": "Ast:GX010312,Goal:GX010311,TO:GX010310,Goal:GX010310,Goal:GX010309,Ast:GX010300,TO:GX010303,Goal:GX010305,Stl:GX010307",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Shaneye",
          "Goal": 0,
          "Assist": 1,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "Ast:GX010298",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Manny",
          "Goal": 0,
          "Assist": 0,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 1,
          "Clip": "TO:GX010301",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Travis",
          "Goal": 0,
          "Assist": 2,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "Stl:GX010311,Ast:GX010311,Ast:GX010309",
          "Team": "Sub",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Sage",
          "Goal": 1,
          "Assist": 0,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "Goal:GX010302,Stl:GX010303",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Eddy",
          "Goal": 0,
          "Assist": 1,
          "Steals": 1,
          "Blocks": 1,
          "Turnovers": 2,
          "Clip": "TO:GX010310,Stl:GX010300,Ast:GX010301,Blk:GX010302,TO:GX010307",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Vivian",
          "Goal": 0,
          "Assist": 0,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 1,
          "Clip": "TO:GX010301",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Glenn",
          "Goal": 2,
          "Assist": 0,
          "Steals": 2,
          "Blocks": 0,
          "Turnovers": 2,
          "Clip": "TO:GX010312,Stl:GX010310,TO:GX010309,Stl:GX010308,Goal:GX010301,Goal:GX010303",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Allie",
          "Goal": 0,
          "Assist": 0,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Justin",
          "Goal": 0,
          "Assist": 1,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 3,
          "Clip": "TO:GX010311,TO:GX010310,TO:GX010300,Stl:GX010301,Ast:GX010302",
          "Team": "Sub",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Max",
          "Goal": 2,
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "5-1 | Legion",
          "Match2": "5-4 | Carp",
          "Match3": "N/A",
          "Winner": "Draw",
          "GameTape": ""
        },
        {
          "Player": "George",
          "Goal": 3,
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Kellie",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Manny",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Shae",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Eddy",
          "Goal": 1,
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "SK",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Diana",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Rachel",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Trevor",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Justin",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Sub",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        }
      ];
    public static playerStatsWeek3 = [
        {
          "Player": "Reuben",
          "Goal": 5,
          "Assist": 2,
          "Steals": 5,
          "Blocks": 0,
          "Turnovers": 2,
          "Clip": "Stl:GX010312,Goal:GX010312,Stl:GX010310,Ast:GX010310,Stl:GX010309,TO:GX010308,Goal:GX010308,Goal:GX010298,Stl:GX010300,Goal:GX010300,Stl:GX010301,TO:GX010302,Ast:GX010305,Goal:GX010307",
          "Team": "Makos",
          "Match1": "5-3 | Makos",
          "Match2": "5-0 | Makos",
          "Match3": "N/A",
          "Winner": "Makos",
          "GameTape": "https://app.box.com/s/gclsfr53u02xyjsqiho9gcdvbtiv4fsw"
        },
        {
          "Player": "James E",
          "Goal": 1,
          "Assist": 2,
          "Steals": 0,
          "Blocks": 1,
          "Turnovers": 1,
          "Clip": "blk:GX010310,Ast:GX010308,TO:GX010300,Goal:GX010304,Ast:GX010307",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Lesley",
          "Goal": 4,
          "Assist": 2,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 2,
          "Clip": "Ast:GX010312,Goal:GX010311,TO:GX010310,Goal:GX010310,Goal:GX010309,Ast:GX010300,TO:GX010303,Goal:GX010305,Stl:GX010307",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Shaneye",
          "Goal": 0,
          "Assist": 1,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "Ast:GX010298",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Manny",
          "Goal": 0,
          "Assist": 0,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 1,
          "Clip": "TO:GX010301",
          "Team": "Makos",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Travis",
          "Goal": 0,
          "Assist": 2,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "Stl:GX010311,Ast:GX010311,Ast:GX010309",
          "Team": "Sub",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Sage",
          "Goal": 1,
          "Assist": 0,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "Goal:GX010302,Stl:GX010303",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Eddy",
          "Goal": 0,
          "Assist": 1,
          "Steals": 1,
          "Blocks": 1,
          "Turnovers": 2,
          "Clip": "TO:GX010310,Stl:GX010300,Ast:GX010301,Blk:GX010302,TO:GX010307",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Vivian",
          "Goal": 0,
          "Assist": 0,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 1,
          "Clip": "TO:GX010301",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Glenn",
          "Goal": 2,
          "Assist": 0,
          "Steals": 2,
          "Blocks": 0,
          "Turnovers": 2,
          "Clip": "TO:GX010312,Stl:GX010310,TO:GX010309,Stl:GX010308,Goal:GX010301,Goal:GX010303",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Allie",
          "Goal": 0,
          "Assist": 0,
          "Steals": 0,
          "Blocks": 0,
          "Turnovers": 0,
          "Clip": "",
          "Team": "Crocs",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Justin",
          "Goal": 0,
          "Assist": 1,
          "Steals": 1,
          "Blocks": 0,
          "Turnovers": 3,
          "Clip": "TO:GX010311,TO:GX010310,TO:GX010300,Stl:GX010301,Ast:GX010302",
          "Team": "Sub",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Max",
          "Goal": 2,
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "5-1 | Legion",
          "Match2": "5-4 | Carp",
          "Match3": "N/A",
          "Winner": "Draw",
          "GameTape": ""
        },
        {
          "Player": "George",
          "Goal": 3,
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Kellie",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Manny",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Shae",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Eddy",
          "Goal": 1,
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Carp",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "SK",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Diana",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Rachel",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Trevor",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Legion",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        },
        {
          "Player": "Justin",
          "Goal": "",
          "Assist": "",
          "Steals": "",
          "Blocks": "",
          "Turnovers": "",
          "Clip": "",
          "Team": "Sub",
          "Match1": "",
          "Match2": "",
          "Match3": "",
          "Winner": "",
          "GameTape": ""
        }
      ];
    public static playerRoster = [
        {
          "Player": "Reuben",
          "LeagueTeam": "Makos",
          "Level": "Pro"
        },
        {
          "Player": "Lesley",
          "LeagueTeam": "Makos",
          "Level": "Pro"
        },
        {
          "Player": "James E",
          "LeagueTeam": "Makos",
          "Level": "Pro"
        },
        {
          "Player": "Travis",
          "LeagueTeam": "Sub",
          "Level": "Pro"
        },
        {
          "Player": "George",
          "LeagueTeam": "Carp",
          "Level": "Pro"
        },
        {
          "Player": "Sage",
          "LeagueTeam": "Chlorine Croc",
          "Level": "Pro"
        },
        {
          "Player": "Glenn",
          "LeagueTeam": "Chlorine Croc",
          "Level": "Pro"
        },
        {
          "Player": "Max",
          "LeagueTeam": "Carp",
          "Level": "Pro"
        },
        {
          "Player": "Shaneye",
          "LeagueTeam": "Makos",
          "Level": "Pro"
        },
        {
          "Player": "Eddy",
          "LeagueTeam": "Chlorine Croc",
          "Level": "Pro"
        },
        {
          "Player": "Allie",
          "LeagueTeam": "Chlorine Croc",
          "Level": "Rookie"
        },
        {
          "Player": "Kellie",
          "LeagueTeam": "Carp",
          "Level": "Pro"
        },
        {
          "Player": "Shae",
          "LeagueTeam": "Carp",
          "Level": "Rookie"
        },
        {
          "Player": "SK",
          "LeagueTeam": "Legion",
          "Level": "Pro"
        },
        {
          "Player": "Diana",
          "LeagueTeam": "Legion",
          "Level": "Rookie"
        },
        {
          "Player": "Rachel",
          "LeagueTeam": "Legion",
          "Level": "Pro"
        },
        {
          "Player": "Trevor",
          "LeagueTeam": "Legion",
          "Level": "Pro"
        },
        {
          "Player": "Manny",
          "LeagueTeam": "Carp",
          "Level": "Pro"
        },
        {
          "Player": "Justin",
          "LeagueTeam": "Sub",
          "Level": "Pro"
        },
        {
          "Player": "Vivian",
          "LeagueTeam": "Chlorine Croc",
          "Level": "Pro"
        }
      ]
  }